name 'issue_tracker_github_cookbook'
maintainer 'Dan Tenenbaum'
maintainer_email 'dtenenba@fredhutch.org'
license 'Artistic 2.0'
description 'Installs/Configures issue_tracker_github'
long_description 'Installs/Configures issue_tracker_github'
version '0.1.5'

depends 'passenger_apache2', '~> 2.3.0'
depends 'apt', '~> 2.9.2'
#depends 'rails'
